### ISSUE TITLE
Couldn't find `clang++` with Xcode Version 6.3.2 (6D2105)

### ISSUE THREAD

**Issue by domesticmouse** [robovm/robovm-studio#9]
Trying to run a iOS sample app threw the follow stack trace while compiling the iOS non interface builder sample app:
```bash
[DEBUG] Building executable /Users/brettmorgan/RobovmStudioProjects/SampleApp/robovm-build/tmp/SampleApp/ios/x86_64/Main
[DEBUG] "2015-07-06 00:16:54.574 xcodebuild[6843:64369] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -o /Users/brettmorgan/RobovmStudioProjects/SampleApp/robovm-build/tmp/SampleApp/ios/x86_64/Main -arch x86_64 -Wl,-filelist,/Users/brettmorgan/RobovmStudioProjects/SampleApp/robovm-build/tmp/SampleApp/ios/x86_64/objects0 -L /Users/brettmorgan/.robovm-sdks/robovm-1.4.0/lib/vm/ios/x86_64 -ObjC -exported_symbols_list /Users/brettmorgan/RobovmStudioProjects/SampleApp/robovm-build/tmp/SampleApp/ios/x86_64/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -mios-simulator-version-min=5.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -lrobovm-bc -force_load /Users/brettmorgan/.robovm-sdks/robovm-1.4.0/lib/vm/ios/x86_64/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework MobileCoreServices -framework UIKit
[ERROR] Couldn't compile app
java.io.IOException: Cannot run program "2015-07-06 00:16:54.574 xcodebuild[6843:64369] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:311)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:206)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:330)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:200)
	at org.robovm.compiler.Linker.link(Linker.java:423)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:462)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 14 more
```

For what it's worth, the referenced binary is present on my disk:

```bash
$ file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++: Mach-O 64-bit executable x86_64
```

```bash
$ ls -l /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
lrwxr-xr-x  1 root  admin  5 Jun 26 11:01 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -> clang
```

**Comment by ashleyj** [comment]
Looks like this might be related to a unity plugin
```
 Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
```

**Comment by badlogic** [comment]
Jupp, the Xcode plugins are at fault. The plugins lack entries in their Info.plist to be compatible with the latest Xcode. You can either try updating the plugins to their latest release, or move them out of the plugin directory temporarily. We'll try to find an automated fix for that on our end, but it's the plugins that are at fault here.

**Comment by badlogic** [comment]
I'm closing this in favor of https://github.com/robovm/robovm/issues/1096
